export const metadataKeywords = [
  "portfolio",
  "profile",
  "software",
  "engineer",
  "frontend",
  "front-end",
  "web",
  "development",
  "website",
  "abdulrahman",
  "react",
  "next",
  "react.js",
  "next.js",
  "typescript",
  "javascript",
  "tailwind",
  "html",
  "css",
  "sass",
  "scss",
  "full-stack",
  "fullstack",
  "node.js",
  "express",
  "angular",
  "react native",
  "sql",
  "mysql",
  "software developer",
  "web developer",
  "frontend developer Egypt",
  "software engineer Egypt",
  "عبدالرحمن إسماعيل",
  "مهندس برمجيات",
  "مطور واجهات",
  "مطور ويب",
  "مطور ريأكت",
  "موقع شخصي",
  "معرض أعمال",
];
